DROP TABLE IF EXISTS address CASCADE;
CREATE TABLE conversations (
	id SERIAL PRIMARY KEY,
	user1Id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  user2Id INTEGER REFERENCES users(id) ON DELETE CASCADE
);